language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script:
  - py.test tests --cov=faucet
  - flake8
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 47421038-adb4-42c9-896d-e48aa816099d